const questions =[
    {
        id:1,
        subject:"Математика",
        question:"1+5",
        option:[
            "1",
            "3",
            "5",
            "6"
        ],
        correctAnswer:3
    },
    {id:2,
        subject:"Математика",
        question:"1+4",
        option:[
            "1",
            "3",
            "5",
            "6"
        ],
        correctAnswer:3
    },
    {
        id:3,
        subject:"Математика",
        question:"1+3",
        option:[
            "1",
            "4",
            "5",
            "6"
        ],
        correctAnswer:2
    },
    {
        id:4,
        subject:"Математика",
        question:"1+2",
        option:[
            "1",
            "3",
            "5",
            "6"
        ],
        correctAnswer:2
    },
     {
        id:5,
        subject:"Математика",
        question:"1+1",
        option:[
            "1",
            "2",
            "5",
            "6"
        ],
        correctAnswer:2
    },
    
]